# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        # Exclude directories that do not contain services
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Ajoutez ou modifiez les définitions de services ci-dessous pour injecter les paramètres
    App\Controller\SmsController:
        arguments:
            $maxSmsLimit: '%env(SMS_MAX_LIMIT)%'      # Injecte la limite max de SMS
            $costPerSms: '%env(SMS_COST_PER_UNIT)%'   # Injecte le coût unitaire des SMS

    App\Service\SmsSender:
        arguments:
            $smsMode: '%env(APP_SMS_MODE)%' # Injecte le mode d'envoi des SMS
            $smsApiKey: '%env(SMS_API_KEY)%'          # Injecte la clé API SMS
            $smsApiEndpoint: '%env(SMS_API_ENDPOINT)%' # Injecte l'endpoint de l'API SMS

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
